### ISSUE TITLE
fanart.tv-api

### ISSUE THREAD

**Issue by ghost** [YunyingYang/AIP-Assessment-3#1]
npm run build fails to minify fanart.tv-api

**Comment by ghost** [comment]
"Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features."

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by mioyuan** [comment]
Solution: copied fanart.tv-api to src/ folder and treat it as part of the application code >_<
